version: '3.8'

services:
  web:
    build: .
    container_name: ctf-platform
    expose:
      - "5050"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_ENV=production
    volumes:
      - instance_data:/app/instance
    restart: unless-stopped

volumes:
  instance_data: